# Generated by Django 5.1.3 on 2024-11-14 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0002_remove_playertask_status_playertask_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=63)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='math_app.task')),
            ],
        ),
    ]
